let responseCodes = {
  SUCCESS: 200,

  INVALID_REQUEST_BODY: 400,
  USER_ALREADY_EXISTS: 401,
  NO_AUTH_TOKEN: 403,
  USER_NOT_FOUND: 404,
  INVALID_PASSWORD: 405,
	CREDENTIALS_REQUIRED : 406,
};

module.exports = responseCodes;
